repos:
-   repo: https://github.com/ambv/black
    rev: 21.11b1
    hooks:
    - id: black
      language_version: python3.8

-   repo: https://github.com/fsouza/autoflake8
    rev: v0.2.2
    hooks:
    -   id: autoflake8

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    - id: flake8
