data_directory: /data
is_gui_enabled: true
is_manager: true
is_worker: true
max_threads: 0
mongo:
  url: mongodb://localhost:27017
redis:
  db: 0
  host: localhost
  password: null
  port: 6379
  username: null
task_queue_uuid: 774659a1-4236-45b1-8547-163676726b79
