version: "3.2"
services:

  redis:
    image: "redis:alpine"
    command: redis-server
    volumes:
      - redis-data:/var/lib/redis
      - ./docker/redis.conf:/usr/local/etc/redis/redis.conf

    environment:
      - REDIS_REPLICATION_MODE=master

    networks:
      - redis

  redis-insgiht:
    image: "redislabs/redisinsight:latest"
    volumes:
      - redisinsight:/db
    ports:
      - 8001:8001

    networks:
      - redis

  audio-archive-manager:
    build: 
      context: ./
      dockerfile: ./docker/Dockerfile
      target: dev
      args:
        base_image: ubuntu:focal

    volumes:
      - ./config:/config
      - ./data:/data
      - ./:/app
    command: "'sleep infinity'"
    ports:
      - 5000:5000

    networks:
      - redis

volumes:
  redis-data:
  redisinsight:

networks:
  redis: