/**
 * Flasger Petstore
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import Attachment from './model/Attachment';
import AudioAttachment from './model/AudioAttachment';
import CatalogEntrySchema from './model/CatalogEntrySchema';
import Group from './model/Group';
import RecordingEntry from './model/RecordingEntry';
import DefaultApi from './api/DefaultApi';


/**
* JS API client generated by OpenAPI Generator.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var FlasgerPetstore = require('index'); // See note below*.
* var xxxSvc = new FlasgerPetstore.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new FlasgerPetstore.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new FlasgerPetstore.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new FlasgerPetstore.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.10
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Attachment model constructor.
     * @property {module:model/Attachment}
     */
    Attachment,

    /**
     * The AudioAttachment model constructor.
     * @property {module:model/AudioAttachment}
     */
    AudioAttachment,

    /**
     * The CatalogEntrySchema model constructor.
     * @property {module:model/CatalogEntrySchema}
     */
    CatalogEntrySchema,

    /**
     * The Group model constructor.
     * @property {module:model/Group}
     */
    Group,

    /**
     * The RecordingEntry model constructor.
     * @property {module:model/RecordingEntry}
     */
    RecordingEntry,

    /**
    * The DefaultApi service constructor.
    * @property {module:api/DefaultApi}
    */
    DefaultApi
};
